language: node_js
node_js:
  - 4.1.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - rm -rf ./coverage
addons:
  code_climate:
    repo_token:
      secure: "k+9w70JBe1iUeK7XLEbNoCJk7J/PKljntwSknlcG0Qu70fCPhTM7Mw7ywPGfr8wdmGgEYjlFRUBm11AM4QOdl2b08mobSqic1VMbM+lXjbTG0x84LXAkrpik7Z2yPRPyd52am7/yxAJ7D4A1K5OmXK3RUcRNF0DAoDqwR9oq7L2yACNCQKmjKOjPuWqj0aTWovWdrKZhlm0BHq4JtIqGxIXycu5X7U9XBTEPvBiepiLSLfr6fBKDxhGRPMl2Ql8GGUDCXCf/LwOvlkFM3Z+y79faiIO/CVqNsfVhk8IsxMEGU0in9w7FQ1Q4DrGshnD6tu+clr3TNZj2nGUMeTWGLsj8fimlarvf/jGnU8il2Rma9lIGEoOAtu/DZxGut0C1yIhKK+tomTnz2QPCjoFZzdKa6ACpWq5NzlEgFMvDLxY1QNJ+KK/XVwhw2oZhKn43Dc5kwlh/p1Sv3IwUtAhlumGMRchclnCVAwaliw932VXsjfrSNK48cYGSBp7ZjLQPsgvXF3ALxp8vP34S8TsO6vTR07qWzg0EgttZdjd3DBl1ggmrgj6Vjb4AnhayIrycjF4z/4VCBSSEC49LiboS2IX8ioOnICrFN76zF6c1d4chNWUp9rAae9bVLlF9NMLDe9liIwymJRnAVpYOy6bKsAEOPmEhRPDmbSnSmnAXMbQ="