language: node_js
node_js:
  - 4.1.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
env:
  - secure: "UNedNf89PwELTeLtgFAlmTf/5rh2qtOojHjsZfpAew+SdfM4xzH5Ui1Lp9L5E0nm0wPWEKGa/Z3wzALOxZFEnRhs9m3OdvYOnzjRdfw54K2y5TvOxENDmNU0uZ502uq9VbMAWycyMlY63+u0eXiYEMXMrdoOH6uOrE+sZhlJNUxVV7WyGC9q0rhUCc2kVLy5WJr9lwN4aaCHkeSiOoJcWHHU/xRQWxxT0OxYPrBFhUpPJs6j06RfDqr40W505Atz8UWV75sHOYtVNVaUDdhFZoVXnLnS3IYCK6W/k717+YI/I4C3OfNtDA2b94GySYICSXq05eVJnIrrYbsqka4WWEsBoUkFkJVIYM31ifxBwthe5+cePDch0XCjnq5FLQcsBeta3yEILW+2vTnaQL4T07WBD+5I6INZlXLrdHuW/pYa5mtcn2LTHWWNej/q7yxAtEiNe+MlO+h+HLZhqNjBp2FBwPUHdGKqIGpzgwAIT1IAlwtuu38WRU7jZrNjU0+fLsJY34jiATkx9+yjqvrg1j2Fr9j43jen59/LgA/soF7B5dBFyVW5hTNw31fQxJuMWb7MZsA3W8qRGPiuWaqzRwTarq7kSJOUaQD+JN4yxiHep+sO/GiK7biOWV77MmB2oU4/U5IJ/rRQk8WcsUnc7iTuTMPef1oamVlQ46+Ydzs="
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - rm -rf ./coverage
addons:
  code_climate:
    repo_token:
      secure: "k+9w70JBe1iUeK7XLEbNoCJk7J/PKljntwSknlcG0Qu70fCPhTM7Mw7ywPGfr8wdmGgEYjlFRUBm11AM4QOdl2b08mobSqic1VMbM+lXjbTG0x84LXAkrpik7Z2yPRPyd52am7/yxAJ7D4A1K5OmXK3RUcRNF0DAoDqwR9oq7L2yACNCQKmjKOjPuWqj0aTWovWdrKZhlm0BHq4JtIqGxIXycu5X7U9XBTEPvBiepiLSLfr6fBKDxhGRPMl2Ql8GGUDCXCf/LwOvlkFM3Z+y79faiIO/CVqNsfVhk8IsxMEGU0in9w7FQ1Q4DrGshnD6tu+clr3TNZj2nGUMeTWGLsj8fimlarvf/jGnU8il2Rma9lIGEoOAtu/DZxGut0C1yIhKK+tomTnz2QPCjoFZzdKa6ACpWq5NzlEgFMvDLxY1QNJ+KK/XVwhw2oZhKn43Dc5kwlh/p1Sv3IwUtAhlumGMRchclnCVAwaliw932VXsjfrSNK48cYGSBp7ZjLQPsgvXF3ALxp8vP34S8TsO6vTR07qWzg0EgttZdjd3DBl1ggmrgj6Vjb4AnhayIrycjF4z/4VCBSSEC49LiboS2IX8ioOnICrFN76zF6c1d4chNWUp9rAae9bVLlF9NMLDe9liIwymJRnAVpYOy6bKsAEOPmEhRPDmbSnSmnAXMbQ="